### PR TITLE
Fix HTML generation

### PR DESCRIPTION
**Pull request by vitorfec**
HTML layout issues fixed

### CODE REVIEW

**Review by dprgarner — APPROVED** [review]
Thanks!

**Comment by kot-lex** [comment]
@dprgarner Could you please publish a new package version with changes from this PR?

**Comment by dprgarner** [comment]
> @dprgarner Could you please publish a new package version with changes from this PR?

@kot-lex I've published the package at version `0.5.2`.

**Comment by pentarix1996** [comment]
@dprgarner 

Good morning, I see that I can not open a Issue, so I ask here. If I wanted to edit the style of the rings (to enlarge the text, for example), how would I proceed?

**Comment by dprgarner** [comment]
@pentarix1996 Feel free to make a PR changing the styling directly. I can see that this would look better with larger text, and I don't think it's particularly disruptive to change this for existing users of the radar.

If you did want to avoid making visual changes by default, you could introduce another _optional_ parameter to the input JSON. Perhaps something nested, like `options.styling.blipFontSize`. This feels like overkill to me, though.

I've enabled issues on this repo now in case anyone else wants to pick them up, but I'm not planning on doing any more development on this package.

**Pull request merged**
